### ISSUE TITLE
0.9.1 Web Installer Issues - need loading icon.

### ISSUE THREAD

**Issue by Xarcell** [pagekit/pagekit#458]
Using the web installer and selecting SQLite and finishing the step where you name the site and add description, it will then slide to a blank screen and sits there doing nothing. If I try to visit index.pip it will just forward to the beginning of the installer. However, when I enter credentials it says the db already exists.

CORRECTION: before submitting this issue, I tried it again and it worked. After the final step there is no loading icon or nothing. It took about 30 seconds to go to the login screen. I think a loading icon or some kind of indicator that the program is working so that users don't think the program just stopped working like I did. Otherwise their will be others who submit similar web installer issues.

Thanks

**Comment by MalteScharenberg** [comment]
@Xarcell There should be a loading indicator. Would be great if you could send me a link to non installed version of pagekit at your server.

**Comment by Xarcell** [comment]
You'll have to use SQLite DB: http://files.xarcell-studios.com/pagekit/

**Comment by MalteScharenberg** [comment]
@Xarcell Your site works for me. Which browser are you using?

**Comment by Xarcell** [comment]
@MalteScharenberg Dang it, being a web designer I should have known to test it in other browsers first. This issue lies in IE touch via Microsoft Surface. So not a major issue, but still a issue.

**Comment by MalteScharenberg** [comment]
We fixed this IE issue: https://github.com/pagekit/pagekit/commit/f3f93ff9c3f119042c5537d897c108c6eb9eab69

Can you check if it's working for you?

**Comment by Xarcell** [comment]
I don't know if the issue has been fixed because now the web installer in throwing a 500 error.

**Comment by MalteScharenberg** [comment]
Thats not good! ;) 
Can you turn on debug mode and provide a more detailed report? 

Installer debug mode can be activated at `app/installer/config.php`. Just set `debug => false` to `true`.

**Comment by Xarcell** [comment]
I turned it on, but it doesn't still show anything. Let me know if you want me to try something else. I did some tinkering of my own, but with no success.
